### PR TITLE
Use WinUIEx tray icon, implement custom Console window and use WinAppSDK notifications

### LINKED ISSUE #653: (Windows) Selecting text in the log window causes the window to stop updating
Selecting text like so in the log window causes it to stop updating, and even closing then re-opening the log window does not fix the issue.
image

This issue has been there for a long time and isn't a regression.

### PR DESCRIPTION
**Pull request by Guerra24**
- Replace H.NotifyIcon with WinUIEx tray icon.
- Implement notifications using WinAppSDK.
- Upgrade to .NET 10.
- Implement a custom *Virtual Console* instead of using the cmd console. Fix https://github.com/Difegue/LANraragi/issues/653.
- Bring in appxmanifest and friends, it will be unused right now but a proper MSIX might be in the horizon™️.

Technically the ConPTY APIs would be the correct ones to implements the virtual console but they are so barely usable (they don't work with CsWin32) and they can't use Process and friends which means even more support code I decided to just use the regular output redirects. There is very minimal console output so it should be fine.

There is a small change required in perl-land so I will be sending a companion pr there.

### CODE REVIEW

File: Karen/Services/Server.cs [hunk 1]
```diff
@@ -22,17 +18,17 @@ public class Server
...
+            VirtualConsole = virtualConsole;
             workDir = Path.Combine(AppContext.BaseDirectory, "lanraragi");
             tempDir = Path.Combine(workDir, "temp");
             logsDir = Path.Combine(workDir, "log");
             PInvoke.AllocConsole();
             PInvoke.SetConsoleOutputCP(65001u);
             PInvoke.SetConsoleTitle("LANraragi Log Console");
-            HideConsole();
-            HideConsoleOnClose.EnableForWindow(PInvoke.GetConsoleWindow());
+            PInvoke.ShowWindow(PInvoke.GetConsoleWindow(), SHOW_WINDOW_CMD.SW_HIDE);
```
Comment (Difegue) [inline Karen/Services/Server.cs:32]: Are those lines still needed if we're not relying on cmd anymore?

**Review by Difegue — CHANGES_REQUESTED** [review]
Looks about right, just one small bit of dead code to remove imo.  

Not quite sure we need the MSIX bits in now -- I'd certainly like to eventually get rid of the WixSharp stuff but as it is it's just dead weight 🤷

File: Karen/Services/Server.cs (hunk 1 above)
Comment (Guerra24) [reply Karen/Services/Server.cs:32]: Oh right I forgot, we need them otherwise redis and perl creates new terminal windows when they start. It is also needed for the ctrl+c stuff to work.

Comment (Difegue) [reply Karen/Services/Server.cs:32]: Ah that makes sense, I forgot about Redis having its own Process loop in there. Doesn't that mean Redis console stuff won't be visible in the new virtual console?

Comment (Guerra24) [reply Karen/Services/Server.cs:32]: Redis logs were never visible, it can only output to one place so it outputs to the log file only.

Comment (Difegue) [reply Karen/Services/Server.cs:32]: Woops you're right, I don't know why I remembered we had redis CLI output, I don't think even the brew version does that.. Good to go then

Comment (Difegue) [inline Karen/Services/Server.cs:32]:
```suggestion
            // This is needed to ensure processes launched by Karen (Redis/Perl) don't spawn additional windows
            PInvoke.ShowWindow(PInvoke.GetConsoleWindow(), SHOW_WINDOW_CMD.SW_HIDE);
```
